export const types = Object.freeze({
  
  FETCH_ITEMS: 'FETCH_ITEMS',
  FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
  FETCH_ITEMS_FAIL: 'FETCH_ITEMS_FAIL',
  
  CREATE_ITEM: 'CREATE_ITEM',
  CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
  CREATE_ITEM_FAIL: 'CREATE_ITEM_FAIL',
  
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ITEM_SUCCESS: 'REMOVE_ITEM_SUCCESS',
  REMOVE_ITEM_FAIL: 'REMOVE_ITEM_FAIL',
  
});
